version: '3'
services:
  core:
    image: "${DHIS2_APPHUB_IMAGE}"
    restart: unless-stopped
    ports:
      - "${DHIS2_APPHUB_PORT}:3000"
    depends_on:
      - "db"
    links: 
      - db
    env_file: .apphub.env
    environment:
      - RDS_DB_PORT=${DHIS2_APPHUB_DB_PORT}
  db:
    image: dhis2/postgres-contrib
    restart: unless-stopped
    environment:
       POSTGRES_DB: app-hub
       POSTGRES_USER: app-hub
       POSTGRES_PASSWORD: app-hub
    command: -p ${DHIS2_APPHUB_DB_PORT}

